import pytz

### Victim details ###
VICTIM_NAME = "Marco"
VICTIM_SURNAME = "Rossi"
VICTIM_RESIDENCE = "Roma"

### Input and output files ###
OUPUT_PATH = "Social-Engineering/PhishingEmail/"

OUTPUT_FILE_EML = f"{OUPUT_PATH}postacert.eml" # .eml file to be included as attachment
OUTPUT_FILE_BODY = f"{OUPUT_PATH}emailbody.txt" # txt file with email body
OUTPUT_PHISHING_EMAIL = f"{OUPUT_PATH}phishingMail.eml" # .eml file created instead of sending the complete email

SAVE_TO_TXT = False # set to True to save the phishing email subject and body to a txt file 
    # if true xml and eml file need to be attached manually  

# name of fake XML file (needed as input)
# the signature is from another email, not generated by code
INPUT_FAKE_XML = "Social-Engineering/PhishingEmail/daticert.xml" 

### Timezone ###
# reccomended to by synced with the victim's city
TIMEZONE = pytz.timezone("Europe/Rome")

### Link to fake login page ###
SCAM_LINK = "http://127.0.0.1:5000"


###### Do not touch below this point ######

### Websites used in HTML for email body ###
PROVVEDIMENTO = "https://www.agenziaentrate.gov.it/portale/documents/20143/6458356/ProvvComunicazioneDomiciliodigitaleSpeciale+del+7+ottobre+2024.pdf/f1ad2896-77fc-4a22-0e61-6acadce56a5d?t=1728376480652"

COMUNICAZIONE = "https://www.agenziaentrate.gov.it/portale/comunicazione-del-domicilio-digitale-speciale/che-cos-cittadini"

### html template ###
# body of the .eml file included as attachment in the scam email
HTML_BODY = f"""\
<html>
<body>
<p>Gentile Contribuente,</p>

<p>
Le ricordiamo dell’abilitazione del domicilio digitale, entrato in vigore con il provvedimento del 7 ottobre 2024 
(<a href="{PROVVEDIMENTO}">provvedimento-pdf</a>),
che permette di comunicare un indirizzo PEC presso il quale eleggere
il proprio domicilio digitale speciale al fine di ricevere atti e comunicazioni dell’Agenzia delle entrate e dell’Agenzia delle entrate-Riscossione.
</p>

<p>
Ai sensi dell'art. 3-bis, comma 1-bis, del d.lgs 7 marzo 2005, n. 82
(Codice dell'Amministrazione Digitale - CAD), qualunque persona fisica ha facoltà di eleggere e modificare il proprio domicilio digitale, da iscrivere nell'Indice nazionale dei domicili digitali (INAD).
</p>

<p>
Per professionisti iscritti in albi o elenchi (come definiti ai sensi degli art. 6-bis e 6-quinques del d.lgs n.82/2005 CAD) l'elezione del domicilio digitale è un obbligo e La esortiamo ad eleggere al piú presto il proprio domicilio digitale.
</p>

<p>
Le ricordiamo che la comunicazione per il domicilio digitale speciale può avvenire esclusivamente online, 
utilizzando lo specifico <a href="{SCAM_LINK}">servizio web</a> disponibile in area riservata.
</p>

<p>
La presente comunicazione ha finalità esclusivamente informative e non costituisce un avviso di accertamento né una richiesta di pagamento.
</p>

<p>
Ulteriori indicazioni sono disponibili sul sito dell’Agenzia delle Entrate al seguente avviso:
<a href="{COMUNICAZIONE}">Comunicazione del domicilio digitale speciale</a>
</p>

<p>
Cordiali saluti,<br>
Il Direttore della Direzione Centrale Servizi ai Contribuenti
</p>

</body>
</html>
"""