import automail
from automail import Victim
from datetime import datetime
import pytz
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

OUTPUT_FILE_EML = "postacert.eml"
COMPLETE_MAIL_FILE = "phishingMail.eml" # email sent here instead of being sent
FAKE_XML_FILE = "daticert.xml" # signature from another email, not generated by code
TIMEZONE = "Europe/Rome"
TZ = pytz.timezone(TIMEZONE)


def send_email(victim: Victim, output: str = COMPLETE_MAIL_FILE, fake_xml: str = FAKE_XML_FILE) -> None:

    date = datetime.now(TZ).strftime("%d-%m-%Y")

    # Create the email
    msg = MIMEMultipart()
    msg["From"] = f"dp.{victim.city}@pce.agenziaentrate.it"
    msg["To"] = f"{victim.mail}"
    msg["Subject"] = (
            "POSTA CERTIFICATA: "
            "NOTIFICA NOTIFICA ELEZIONE DOMICILIO DIGITALE "
            "TI8 Q01358/2026 "
            f"[ENTRATE|AGEDP|REGISTRO UFFICIALE|236913|{date}]"
            "[358965823|349749437]"
        )

    body = automail.write_email(victim, OUTPUT_FILE_EML, save_to_txt=False)
    msg.attach(MIMEText(body, "plain"))

    # Attach the .eml file
    with open(OUTPUT_FILE_EML, "rb") as attachment:
        eml_part = MIMEBase("application", "octet-stream")
        eml_part.set_payload(attachment.read())

    encoders.encode_base64(eml_part)

    eml_part.add_header(
        "Content-Disposition",
        f'attachment; filename="{OUTPUT_FILE_EML}"'
    )
    msg.attach(eml_part)

    # Attach the fake certificate
    try: 
        with open(fake_xml, "rb") as attachment:
                xml_part = MIMEBase("application", "octet-stream")
                xml_part.set_payload(attachment.read())

        encoders.encode_base64(xml_part)

        xml_part.add_header(
            "Content-Disposition",
            f'attachment; filename="{fake_xml}"'
        )
        msg.attach(xml_part)
    except OSError as e:
        print(f"No .xml file found, please provide a '{FAKE_XML_FILE}' file")
        print("to specify name of xml file, usage: sendMail(victim, output, fake_xml)")
        exit
    else: 
        # Save email
        with open(output, "w", encoding="utf-8", newline="\n") as f:
            f.write(msg.as_string())

if __name__ == "__main__":
    victim = Victim("Riccardo", "Ambesi Impiombato", "Udine")
    send_email(victim)
